name: "Build"

on:
  pull_request:
  push:

jobs:
  stack2nix:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v8
    - name: Cachix
      uses: cachix/cachix-action@v6
      with:
        name: pbogdan
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix build -L

